# Default values for minio-operator.

operator:
  image:
    repository: minio/operator
    tag: v4.3.7
    pullPolicy: IfNotPresent
  imagePullSecrets: [ ]
  initcontainers: [ ]
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroup: 1000
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
      ephemeral-storage: 500Mi

console:
  image:
    repository: minio/console
    tag: v0.12.3
    pullPolicy: IfNotPresent
  imagePullSecrets: [ ]
  initcontainers: [ ]
  replicaCount: 1
  nodeSelector: { }
  affinity: { }
  tolerations: [ ]
  topologySpreadConstraints: [ ]
  resources: { }
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  ingress:
    enabled: true
    labels: { }
    annotations: { }
    tls: []
    host: minio-operator-console.k8s-workshop.tk
    path: /

tenants:
  # Tenant name
  - name: minio
    image:
      repository: minio/minio
      tag: RELEASE.2021-10-06T23-36-31Z
      pullPolicy: IfNotPresent
    namespace: minio-tenant
    imagePullSecret: { }
    scheduler: { }
    pools:
      - servers: 4
        size: 10Gi
        storageClassName: nfs-client-wait
        tolerations: { }
        nodeSelector: { }
        affinity: { }
        resources: { }
        securityContext: { }
        topologySpreadConstraints: [ ]
    mountPath: /export
    subPath: /data
    secrets:
      enabled: true
      name: minio1-secret
      accessKey: minio
      secretKey: minio123
    metrics:
      enabled: false
      port: 9000
    certificate:
      externalCaCertSecret: { }
      externalCertSecret: { }
      requestAutoCert: true
      certConfig: { }
    s3:
      bucketDNS: false
    podManagementPolicy: Parallel
    serviceMetadata: { }
    env: { }
    priorityClassName: ""

