apiVersion: v1
kind: Secret
metadata:
  name: database-env
  namespace: nextcloud
stringData:
  MYSQL_ROOT_PASSWORD: "4ded784a9dcd3e988f5e5a187a8f1e"
  MYSQL_PASSWORD: "b309774fcfc32b2b32843f2b44c93d"
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  MYSQL_HOST: "database"

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-env
  namespace: nextcloud
stringData:
  APACHE_DISABLE_REWRITE_IP: "1"
  OBJECTSTORE_S3_HOST: "minio.k8s-workshop.tk"
  OBJECTSTORE_S3_BUCKET: "nextcloud"
  OBJECTSTORE_S3_KEY: "minio"
  OBJECTSTORE_S3_SECRET: "minio123"
  OBJECTSTORE_S3_USEPATH_STYLE: "true"
  OBJECTSTORE_S3_SSL: "true"
  OBJECTSTORE_S3_REGION: "us-east-1"


